name: Publish

on:
  push:
    tags:
      - "v*"

env:
  proj: "TotkRegistryToolkit"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      release: ${{ steps.release.outputs.upload_url }}
      version: ${{ steps.version.outputs.version-without-v }}

    steps:
      - name: Get Version
        uses: battila7/get-version-action@v2.2.1
        id: version

      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ env.proj }} - ${{ steps.version.outputs.version }}
          prerelease: ${{ contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') || contains(steps.version.outputs.version, 'rc') }}

  build:
    needs: release
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: Windows (x64)
            os: ubuntu-latest
            runtime: win-x64
          - name: Windows (arm64)
            os: ubuntu-latest
            runtime: win-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Build
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }} \
          -c Release \
          -o ${{ matrix.config.runtime }} \
          -r ${{ matrix.config.runtime }} \
          --sc false \
          --version-suffix ${{ needs.release.outputs.version }} \
          -p:DebugType=none \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishSingleFile=true \
          -p:Version=${{ needs.release.outputs.version }} \

      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ needs.release.outputs.release }}
          asset_path: ${{ matrix.config.runtime }}/${{ env.proj }}.exe
          asset_name: ${{ matrix.config.runtime }}.exe
          asset_content_type: application/zip

      - name: Patch Setup
        shell: bash
        run: |-
          sed -i 's/win-x64/${{ matrix.config.runtime }}/g' Setup.bat

      - name: Upload Setup Script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ needs.release.outputs.release }}
          asset_path: Setup.bat
          asset_name: Setup-${{ matrix.config.runtime }}.bat
          asset_content_type: application/zip
